#!/bin/sh

export POSIXLY_CORRECT=yes
if [ -z "$XTF_PROFIT" ]; then
    export XTF_PROFIT=20
fi

filtr(){
    if [ "$1" = "-a" ] ; then   #add processing for several filtres
        filtr_a=$1
        shift
        after=$1
        shift
        prikaz "$@"
    elif [ "$1" = "-b" ] ; then
        filtr_b=$1
        shift
        before=$1
        shift 
        prikaz "$@"
    elif [ "$1" = "-c" ] ; then
        filtr_c=$1
        shift
        currency=$1
        shift 
        prikaz "$@"   

    else
        prikaz "$@"
    fi

}

prikaz(){
    if [ "$1" = "list" ] || [ "$1" = "list-currency" ] || [ "$1" = "status" ] || [ "$1" = "profit" ]; then
        prikaz=$1
        shift
        uzivatel "$@"
    elif [ "$1" = "-a" ] || [ "$1" = "-b" ] || [ "$1" = "-c" ] ; then #for several filtres 
        filtr "$@"  
    else
        prikaz="list"
        uzivatel "$@"
    fi
}

uzivatel(){
    name=$1
    shift
    log "$@"
}

log(){
    if [ -z "$1" ]; then
        echo "no logfile" >&2
        exit 1 
    fi
    for arg in "$@"; do #for several logs
        if [ -f "$arg" ]; then  #chek if this is a file and write list of users
            case "$arg" in
            *.gz) 
                if [ -n "$newlist" ]; then   
                    appended=$(zcat "$arg")
                    newlist="$newlist""$appended"  #on my systen \n works correctly, on merlin no
                    # newlist=$(echo "$newlist" | cat "$appended_content")
                    # ЧОМУСЬ ВИНИКАЮТЬ ПОЧТОРКИ ЯКЩО ВЗЯТИ ЗІП ФАЙЛ І ЗВИЧАЙНИЙ ФАЙЛ З ПРІКАЗЕМ ЛІСТ
                else
                    newlist=$(zcat "$arg")
                fi
                ;;
            *) 
                if [ -n "$newlist" ]; then
                    newlist=$(echo "$newlist" | cat - "$arg")
                else
                    newlist=$(cat "$arg")
                fi
                ;;
            esac
            #filtering 
            if [ "$filtr_a" ]; then
                newlist=$(echo "$newlist" | awk -v date="$after" -F ';' '$2 > date' )
            fi
            if [ "$filtr_b" ]; then
                newlist=$(echo "$newlist" | awk -v date="$before" -F ';' '$2 < date' )
            fi
            if [ "$filtr_c" ]; then
                newlist=$(echo "$newlist" | awk -v currency="$currency" -F ';' '$3 == currency' )
            fi
        else
            echo "$1 is not a file" >&2
            exit 1
        fi

    done     
            if [ "$prikaz" = "list-currency" ]; then
                echo "$newlist" | grep "$name"| awk -F ';' '{print $3}' | sort -u    
            elif [ "$prikaz" = "list" ]; then
                echo "$newlist" | grep "$name" 
            elif [ "$prikaz" = "status" ]; then
                echo "$newlist" | grep "$name"| awk -F ';' '
                    {
                        # Якщо ця валюта вже була зустрінута, додати баланс до суми для цієї валюти
                        if ($3 in currency_arr) {
                            currency_arr[$3] += $4
                        } else {
                            # Інакше створити новий запис для цієї валюти
                            currency_arr[$3] = $4
                        }
                    }
                    END {
                        # Вивести суму для кожної валюти
                        for (currency in currency_arr) {
                            printf "%s : %.4f\n" , currency , currency_arr[currency]
                        }
                    }
                ' | sort  
            elif [ "$prikaz" = "profit" ]; then
                echo "$newlist" | grep "$name" | awk -F ';' -v XTF_PROFIT="$XTF_PROFIT" '
                    {
                        # Якщо ця валюта вже була зустрінута, додати баланс до суми для цієї валюти
                        if ($3 in currency_arr) {
                            currency_arr[$3] += $4
                        } else {
                            # Інакше створити новий запис для цієї валюти
                            currency_arr[$3] = $4
                        }
                    }
                    END {
                        # Вивести суму для кожної валюти
                        for (currency in currency_arr) {
                            if (currency_arr[currency] > 0){
                                num = currency_arr[currency] * XTF_PROFIT * 0.01
                                currency_arr[$3] +=  num
                            }
                            printf "%s : %.4f\n" , currency , currency_arr[currency]
                        }
                    }
                ' | sort

            fi
}

if [ "$1" = "-hl" ] || [ "$1" = "--help" ]; then
    echo "xtf [-h|--help] [FILTR] [PŘÍKAZ] UŽIVATEL LOG [LOG2 [...] "
    echo "
PŘÍKAZ může být jeden z:
    list – výpis záznamů pro daného uživatele.
    list-currency – výpis seřazeného seznamu vyskytujících se měn.
    status – výpis skutečného stavu účtu seskupeného a seřazeného dle jednotlivých měn.
    profit – výpis stavu účtu zákazníka se započítaným fiktivním výnosem.

FILTR může být kombinace následujících:
    -a DATETIME – after: jsou uvažovány pouze záznamy PO tomto datu a čase (bez něj). DATETIME je formátu YYYY-MM-DD HH:MM:SS.
    -b DATETIME – before: jsou uvažovány pouze záznamy PŘED tímto datem a časem (bez něj).
    -c CURRENCY – jsou uvažovány pouze záznamy odpovídající dané měně."

elif [ -z "$1" ]; then
    echo "no arguments" >&2
    exit 1
else
    filtr "$@"

fi
