#!/bin/sh

export POSIXLY_CORRECT=yes
# if [ -z "${XTF_PROFIT:-}" ]; then
#     echo "set profit to 20"
export XTF_PROFIT=20
# # fi
# echo "hodnota = $XTF_PROFIT "
filtr(){
    if [ "$1" = "-a" ] ; then   #add processing for several filtres
        filtr_a=$1
        shift
        after=$1
        shift
        prikaz "$@"
    elif [ "$1" = "-b" ] ; then
        filtr_b=$1
        shift
        before=$1
        shift 
        prikaz "$@"
    elif [ "$1" = "-c" ] ; then
        filtr_c=$1
        shift
        currency=$1
        shift 
        prikaz "$@"   

    else
        prikaz "$@"
    fi

}

prikaz(){
    if [ "$1" = "list" ] || [ "$1" = "list-currency" ] || [ "$1" = "status" ] || [ "$1" = "profit" ]; then
        prikaz=$1
        shift
        uzivatel "$@"
    elif [ "$1" = "-a" ] || [ "$1" = "-b" ] || [ "$1" = "-c" ] ; then #for several filtres 
        filtr "$@"   
    else
        prikaz="list"
        uzivatel "$@"
    fi
}

uzivatel(){
    name=$1
    shift
    log "$@"
}
# filtrovani(){

#     if [ "$filtr" = "-a" ] ; then   
#         newlist=$(echo $1 | awk -F ';' -v date="$filtr_data" '{
#             if (date > $2) {
#                 print $0
#             }
#         }')
#     # elif  [ "$filtr" = "-b" ] ; then
#     #     $1=$(echo "$1" | awk -F "," -v date="$filtr" '{
#     #         if (date <= $2) {
#     #             print $0
#     #         }
#     #     }')
#     # elif  [ "$filtr" = "-c" ] ; then
        

#     # elif [ -z "$filtr" ] ; then
        
#     fi
# }

log(){
    if [ -z "$1" ]; then
        echo "no logfile"
    fi
    for arg in "$@"; do #for several logs


        if [ -f "$arg" ]; then  #chek if this is a file and write list of users
            # newlist=$(cat "$arg") #for processing multiple filtres

            if [ -n "$newlist" ]; then
                newlist=$(echo "$newlist" | cat - "$arg")
            else
                newlist=$(cat "$arg")
            fi
            # echo "ontain of newlist " "$newlist"
            if [ "$filtr_a" ]; then
                newlist=$(echo "$newlist" | awk -v date="$after" -F ';' '$2 > date' )
                # echo "$newlist"
            fi
            if [ "$filtr_b" ]; then
                newlist=$(echo "$newlist" | awk -v date="$before" -F ';' '$2 < date' )
                # echo "$newlist"
            fi
            if [ "$filtr_c" ]; then
                # newlist=$(awk -v currency="$currency" -F ';' '$3 == currency' "$newlist")
                newlist=$(echo "$newlist" | awk -v currency="$currency" -F ';' '$3 == currency' )
                # echo "$newlist"
            fi
        else
            echo "$1 is not a file"   
            #add standart error output
        fi
    done         
            if [ "$prikaz" = "list" ]; then
                # grep "$name" "$arg"
                # newlist=$(grep "$name" "$arg")
                # newlist=$(awk -v name="$name" '$0 ~ name')
                # echo "$newlist"
                # Пошук рядків, що містять задане ім'я у змінній newlist
                echo "$newlist" | grep "$name" | sort -u
                # echo "$newlist" | grep "$name"
            elif [ "$prikaz" = "list-currency" ]; then
                # grep "$name" "$arg" | awk -F ';' '{print $3}' | sort -u  #DOES NOT SORT IF THE ARE MULTIPLE FILES
                #search all lines with name and use awk to divide row by ; 
                #and write third part which contains currency
                # echo "$newlist" | grep "$name"| awk -F ';' '{print $3}' | sort -u #DOES NOT SORT IF THE ARE MULTIPLE FILES
                echo "$newlist" | grep "$name"| awk -F ';' '{print $3}' | sort -u
            elif [ "$prikaz" = "status" ]; then
                #DOES NOT add IF THE ARE MULTIPLE FILES
                echo "$newlist" | grep "$name"| awk -F ';' '
                    {
                        # Якщо ця валюта вже була зустрінута, додати баланс до суми для цієї валюти
                        if ($3 in currency_sum) {
                            currency_sum[$3] += $4
                        } else {
                            # Інакше створити новий запис для цієї валюти
                            currency_sum[$3] = $4
                        }
                    }
                    END {
                        # Вивести суму для кожної валюти
                        for (currency in currency_sum) {
                            print currency " : " currency_sum[currency]
                        }
                    }
                ' | sort  #i hope this sort will sort currency by alfabet 
                
                

            elif [ "$prikaz" = "profit" ]; then
                echo "$newlist" | grep "$name" | awk -F ';' -v XTF_PROFIT="$XTF_PROFIT" '
                    {
                        # Якщо ця валюта вже була зустрінута, додати баланс до суми для цієї валюти
                        if ($3 in currency_sum) {
                            currency_sum[$3] += $4
                        } else {
                            # Інакше створити новий запис для цієї валюти
                            currency_sum[$3] = $4
                        }
                    }
                    END {
                        # Вивести суму для кожної валюти
                        for (currency in currency_sum) {
                            if (currency_sum[currency] > 0){
                                # num = sprintf("%.4f", currency_sum[currency] * XTF_PROFIT * 0.01 )   #ВАРІАНТ ІЗ ЗАОКРУГЛЕННЯ, НЕ ВПЕВНЕНА ЩО ВІН  ПОТРІБНИЙ
                                num = currency_sum[currency] * XTF_PROFIT * 0.01
                                currency_sum[$3] +=  num
                            }
                            print currency " : " currency_sum[currency] 
                        }
                    }
                ' | sort

            fi
        # else
        #     echo "$1 is not a file"   
        #     #add standart error output
        # fi
        
    # done
    # echo "$newlist"
}


if [ "$1" = "-hl" ] || [ "$1" = "--help" ]; then
    echo "xtf [-h|--help] [FILTR] [PŘÍKAZ] UŽIVATEL LOG [LOG2 [...] "
elif [ -z "$1" ]; then
    echo "no arguments"
else
    filtr "$@"

fi